<?php

// TO DO:
// 1. fix everything
// 2. write at least two more questions
// 3. make suggestions based on questions

function pastry_quiz_menu() {
    $items['quiz'] = array(
        'title' => 'What should I eat!?',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('start_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['quiz_question_1'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('quiz_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}
function quiz_form() {
  $form['gluten'] = array(
      '#title' => 'Gluten Intollerance',
      '#type' => 'radios',
      '#description' => t('Are you gluten intollerant?'),
      '#options' => array(
          t('Yes'),
          t('No'),
      ),
      '#required' => TRUE,
  );

  $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'submit',
  );

  return $form;
}

function start_form() {
    // $form['gluten'] = array(
    //     '#title' => 'Gluten Intollerance',
    //     '#type' => 'radios',
    //     '#description' => t('Are you gluten intollerant?'),
    //     '#options' => array(
    //         t('Yes'),
    //         t('No'),
    //     ),
    //     '#required' => TRUE,
    // );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
    );

    return $form;
}

function start_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'quiz_question_1';
}
