<?php
function bakery_user_menu() {
    $items = array();
    $items['welcome_user'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function welcome_user() {
    return "<p>Welcome to Cameron's Bakery!</p>";
}

function bakery_user_user_login(&$edit, $account) {
    $_GET['destination'] = 'welcome_user';
}
