<?php
function titlecase_menu() {
    $items = array();
    $items['titlecase'] = array(
        'title' => 'Title Case Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('titlecase_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_success'] = array(
        'title' => 'Success',
        'page callback' => 'titlecase_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function titlecase_form() {
    $form['input'] = array(
        '#title' => 'Enter in a title to convert',
        '#type' => 'textfield',
        '#description' => t('Please enter your title'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Make Title Case',
    );
    return $form;
}

function make_title_case($input){

    $ignore = ["a", "an", "the", "and", "but", "or", "nor", "at", "by", "for", "from", "in", "into", "of", "off", "on", "onto", "out", "up", "with", "to", "as"];

    // make all letters in the input phrase lower case and separate them by space so that we have an array of words.
    $input_exploded = explode(' ', strtolower($input));
    $output_phrase = [];
    foreach ($input_exploded as $index => $word) {
        //if we're on the first word, or the word is not contained in the ignore array, capitalize.
        //Else, just push the word into the output phrase unchanged.
        if ($index == 0 || !in_array($word, $ignore)) {
            array_push($output_phrase, ucfirst($word));
        } else {
            array_push($output_phrase, $word);
        }
    }

    return implode(' ', $output_phrase);
}

function titlecase_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];
    $result = make_title_case($input);
    $_SESSION['title'] = $result;

    $form_state['redirect'] = 'title_success';
}

function titlecase_success() {
    $title = $_SESSION['title'];
    return '<p>Your titlecased string: ' . $title . '</p>';
}
