<?php
//


function bakery_user_menu() {
    // blank items array was missing
    $items = array();
    //should be welcome_user?
    $items['welcome_user'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function bakery_user_login(&$edit, $account) {
  // not sure if this part should be =>
    $_GET['destination'] = 'welcome_user';
}

function welcome_user() {
    return "<p>Welcome to Cameron's Bakery!</p>";
}
