<?php
/**
 * Create a Field Collection field and attach collection node reference
 */
function _create_field_collection() {
  $t = get_t();
  
  $fields_array = array(
    array(
      'field' => array(
        'field_name' => 'custom_collection',
        'label' => $t('BIR Collection Nodes'),
        'cardinality' => -1,
        'type' => 'field_collection',
      ),
      'instance' => array(
        'field_name' => 'bir_collection',
        'entity_type' => 'node',
        'bundle' => 'article',
        'label' => $t('BIR Collection Nodes'),
        'description' => '',
        'widget' => array('type' => 'field_collection_embed'),
        'required' => 1,
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'bir_collection_node',
        'type' => 'node_reference',
        'label' => '',
        'cardinality' => 1,
        'settings' => array(
          'referenceable_types' => array(
            'bir_specimen' => 'bir_specimen',
            'bir_image' => 'bir_image',
            'bir_locality' => 'bir_locality',
            'bir_view' => 'bir_view',
          ),
        ),
      ),
      'instance' => array(
        'field_name' => 'bir_collection_node',
        'entity_type' => 'field_collection_item',
        'bundle' => 'bir_collection',
        'label' => '',
        'cardinality' => 1,
        'description' => '',
        'widget' => array('type' => 'node_reference_autocomplete'),
        'display' => array('default' => array('type' => 'node_reference_default')),
      )
    ),
  );
  
  // Loop through fields array and create field and instance
  foreach ($fields_array as $field) {
    // Check if field already exists
    if (!field_info_field($field['field']['field_name'])) {
      field_create_field($field['field']);
    }

    // Check if instance exists
    if (!field_info_instance($field['instance']['entity_type'], $field['instance']['field_name'], $field['instance']['bundle'])) {
      field_create_instance($field['instance']);
    }
  }  
}

// Create node
$node = new stdClass();
$node->type = 'article';
node_object_prepare($node);
$node->title = 'Testing Article Creation';
$node->language = LANGUAGE_NONE;
$node->status = 1;
$node->uid = 1;
node_save($node);

// Create and save field collection for node
$field_collection_item = entity_create('field_collection_item', array('field_name' => 'bir_collection'));
$field_collection_item->setHostEntity('node', $node);
$field_collection_item->bir_collection_node[LANGUAGE_NONE][]['nid'] = 99999;
$field_collection_item->save();
