<?php
function custom_collection_menu(){
    $items = array();
    $items['/'] = array(
        'page callback' => 'custom_collection_node_load',
        'access callback' => TRUE,
    );
    return $items;
}

function custom_collection_node_load($nodes, $types){
        kpr(commerce_product_entity_info());
        kpr($nodes);
        kpr($types);    
        
        $product = commerce_product_type_load('product');
        kpr($product);    
  
}
